### ISSUE TITLE
Support both msw and nock

### ISSUE THREAD

**Issue by mikicho** [levino/mock-jwks#207]
I use Nock, and v3 sort of broke my tests. Although I have fixed them, this solution is not sustainable in the long term. 
WDYT about injecting the mock methods (start/stop)? or support both with `msw` be the default?
These libraries are widely used and should be easy to integrate. 
If you agree, I can open a pull request.

**Comment by levino** [comment]
Hi @mikicho, thank you for reporting on your issues. Could you please elaborate on the problems you experience using the library? Maybe you could create a minimal reproduction repository.

In general your suggestion might be a good idea, but I do not change code without understanding the bug first. And I also do not see "dependency inject the network mocking layer library" as a feature tbh but a compatibility mechanism, so I would only introduce it, if there is no other way to solve the issue you are experiencing.

**Comment by mikicho** [comment]
@levino it causes 2 problems:
1. I use `nock.disableNetConnect()` which causes the request to the jwks server to fail. because msw is after on the network layer.
2. They may interfere with each other in later versions.

**Comment by levino** [comment]
I thought about it and so far, I am sorry but I decided, I will not support the injection / choice of the mocking tool. The usage of `nock` was never a feature, but an implementation detail which already created some issues (for example that one had to install nock in a specific version as a peer dependency instead of a dependency because running two versions of nock at the same time would create errors). `msw` will replace `nock` in the near feature, as far as I see it. It is just cleaner, better documented and also maintained. The fact that you have issues using `mock-jwks` while running `nock` for other things at the same time is unfortunate. I recommend using version 2. I will fix bugs for version 2 also in the future, if there are any, so I think this compromise should be okay. Even more I would recommend to stop using `nock` in your project and use `msw` instead.

If you really think that your usecase is very common and it is important to keep `mock-jwks` compatible with `nock` I would need a demo repository with some meaningful test in order to understand what exactly you are trying to achieve and that it cannot be achieved in a different way.

**Comment by mikicho** [comment]
> Even more I would recommend to stop using nock in your project and use msw instead

IMO, `msw` != `nock`. they work completely differently, Nock has interceptors and stack and lets you define the mocks inside the tests. `msw` has a similar approach to `json-server` and `stubby`.

I am considering creating a new package by forking this repository and naming it either "nock-jwks" or "mock-jwks-nock". I would then merge any new commits from the original repository. I believe that maintaining this new package should not require much effort since the mocking mechanism is not the main feature of the package. Perhaps some tests may need to be adjusted. What are your thoughts on this option?

**Comment by levino** [comment]
I think you are too focused on `nock` itself and not on the problem you are trying to solve. As long as you do not provide an example repo, I really cannot see, if your usage of `nock` is justified.

This all reminded me of something btw: If you use `disableNetConnect`, you will also not be able to locally test your rest api since even requests to localhost will be forbidden. But `mock-jwks` is a tool to test your rest api, so I would rather think you were doing something like the following as from the [docs](https://github.com/nock/nock#enabledisable-real-http-requests) of `nock`:
```
nock.disableNetConnect()
// Allow localhost connections so we can test local routes and mock servers.
nock.enableNetConnect('127.0.0.1')
```
You could also call `enableNetConnect` for the jwks host and then `msw` should kick in, should it not? I am not sure, but maybe you have to use a predicate function in order to enable multiple hostsnames like so:
```
nock.enableNetConnect(
  host => host.includes('amazon.com') || host.includes('github.com')
)
```

**Comment by levino** [comment]
> > ...  I really cannot see, if your usage of nock is justified
> 
> Here [in an example](https://github.com/testjavascript/nodejs-integration-tests-best-practices/blob/master/example-application/test/basic-tests.test.js#L162). Can I do something similar with `msw`?

[Yes.](https://mswjs.io/docs/api/setup-server/use#runtime-request-handler). Also have a look at [this](https://mswjs.io/docs/api/setup-server#examples). It might be somewhat more verbose than `nock` but you can wrap stuff in convenience functions as you like and should be able to quite easily be able to build the `nock` interface with `msw`. But now we are disussing `nock` vs `msw` which is not what `mock-jwks` about. **It is not a `nock` addon or plugin.** `nock` was just a choice on how to do the mocking. I will also continue to use `nock` in my projects, because I really like the `nockBack` mode to record and playback requests to third party services. A feature which I think `msw` does not provide. Adding the exceptions for the `disableNetConnect` for the jwks host is an okay thing to do imo.

I will keep your feed back in mind. If anyone else has issues or opinions about `msw` and people really do prefer `mock-jwks` to use `nock` under the hood, I will reconsider. Please raise your voices if you read this. Until then, I will keep the library as is.

On the matter of a fork: Please feel free to do so. I will take no offense. For me that is the idea: Create good libraries, let them compete and see which one attracts the most usage. Maybe also a good way to find out if the community wants `nock` in this badly.

**Comment by mikicho** [comment]
I agree. Thanks for the response and the patience!
