### ISSUE TITLE
Allowing key overrides

### ISSUE THREAD

**Issue by slifty** [levino/mock-jwks#218]
I wanted to use `mock-jwks` to test my service to ensure that it would reject a jwt that had the correct issuer values BUT was generated using a "bad" certificate (e.g. testing to make sure someone couldn't just make a jwt attempting to lie about the origin).

I had written a test that would spin up a second mock jwks instance, generate a token, and then switch back to the "original" mock, but realized `mock-jwks` [uses a hard coded key pair](https://github.com/levino/mock-jwks/blob/aa706ffd19e9ef80b63045da6a91ec3179b99081/src/tools.ts#L10-L48) and so both mocked servers are using the same certs.

Would it be possible to either (1) generate the certificate instead of hard coding it, so each server instance is distinct, or (2) make it possible to pass in a key pair in the case that I want to override it for a given test?

**Comment by levino** [comment]
Hi @slifty,
I have thought a bit about it and at the moment, I am hesitant to implement your proposed changes. Let us look a the details

# Use case

You want to write a test that goes as follows:
- Create a jwt and sign it with a private key which is different from the one that `mock-jwks` is using.
- Query your api with that jwt.

You have the following expectation:
- Your api denies access (based on the fact that the jwt was not signed with the key provided by `mock-jwks`.

# Thoughts

- This test does not strictly test what `mock-jwks` is designed for. You are testing that the signature verification works correctly. However that is not really a test for your configuration but rather for the implementation of the code which checks the validity of the signature. This test could only fail if your code maybe does not check the signature at all or something but certainly if the key delivered by `mock-jwks` is used then this check will fail. I do not think that this test really helps, especially because to "be really sure" you would have to test with all possible different keys or something which of course is infeasible.
- You can quickly sign an arbitrary jwt with [`jsonwebtoken`](https://www.npmjs.com/package/jsonwebtoken#jwtsignpayload-secretorprivatekey-options-callback) for this test which is what `mock-jwks` is doing under the hood. So why bother creating a whole `mock-jwks` instance for this? To me this sounds a bit like buying a tesla because one can use it charge ones phone. Doable, but overkill.
- If I were to allow to feed an arbitrary private key to `mock-jwks`, people will probably eventually feed it their production private key. This is of course a dangerous mistake, but people are people and some of them are just new on the job, etc. I deliberately try to make this library as unusable for production code usage as possible. The reason is that I fear that there is some upstream code which has bugs or backdoors or whatnot. I do not want be be constantly on the lookout for vulnerabilities because I am paranoid that my code will make the users suffer. So I would only introduce this additional surface for very good reasons.

# Conclusion

At the moment I will not act on your proposed changes. If you agree with my reasoning and can implement your test with `jsonwebtoken` then please close this issue. If you still think there are good reasons to extend the interface of the library, please elaborate.

**Comment by slifty** [comment]
@levino thank you so much for taking the idea into consideration and for such a detailed and thoughtful reply!  I completely agree with what you wrote, and appreciate the suggestions.  Your second point in particular is very well taken; there is no need for an entire server to be created to generate a single "bad" web token -- I can simply do that once and hard code the bad token in my test.

I'll close the issue!
